name: Test on push and publish

on:
  workflow_call:
    secrets:
      github-token:
        required: true
      credentials:
        required: true

jobs:

  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@1.0.3
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.3
        with:
          credentials: "${{ secrets.TEST_SECRET }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"

  debug:
    name: Debug by establishing a connection to runner
    runs-on: ubuntu-latest
    steps:
      # temporarily allow to ssh to debug this action
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 20
        with:
          limit-access-to-actor: true
          credentials: ${{ secrets.TEST_SECRET }}
